### ISSUE TITLE
Equations?

### ISSUE THREAD

**Issue by cpbridges** [PW-Sat2/HAMRadio#8]
Very nice tools here! Can you point me to the code where there are the telemetry point equations? Especially for any beacon. I'd like to use this suite as a test for my own toolchains in parallel.

Also, can you confirm there an offline mode for people to sit in their shacks and see the decoded data?

Thanks in advance! 73s C

**Comment by begreeen** [comment]
> Can you point me to the code where there are the telemetry point equations? Especially for any beacon. I'd like to use this suite as a test for my own toolchains in parallel.

Telemetry (beacon) structure is described [here](https://github.com/PW-Sat2/FramePayloadDecoder#i-would-like-to-write-telemetry-frames-parser-from-scratch-what-is-the-format). In this repository is also located python-based parser for those frames. There are also provided examples (ax.25 information field content!).
Equations are coded in [those files](https://github.com/PW-Sat2/PWSat2OBC/tree/master/integration_tests/emulator/beacon_parser).


> Also, can you confirm there an offline mode for people to sit in their shacks and see the decoded data?

Sure! Just toggle the button [Auto upload enabled](https://user-images.githubusercontent.com/6267528/44951347-5f146400-ae62-11e8-923d-aaf61704fa38.png). Frames will be saved locally in `saved_frames` directory - an application will show you a popup window with a path/filename - [as shown here](https://github.com/PW-Sat2/HAMRadio/wiki/Cloud-uploader#exiting-with-not-completed-uploads).

Then, you can run the application later on (when you have the internet connection) and just load mentioned `.frames` file using [this button](https://github.com/PW-Sat2/HAMRadio/wiki/Received-frames-list-and-%22.frames%22-files#loading-saved-frames-file). Make sure that `Auto upload enabled` button is pushed and the frames should be uploaded immediately.

If you have any other questions don't hesitate to ask :)

**Comment by cpbridges** [comment]
Excellent! Thanks for the info - I'm sure hams will be super pleased with this response. 73s C
